### ISSUE TITLE
Is there a way to find out if the previous cron is still running?

### ISSUE THREAD

**Issue by maximedegreve** [MihaelIsaev/VaporCron#2]
For example if you run a cron every 15 min you might want to check if the previous cron is finished or not.

**Comment by MihaelIsaev** [comment]
That's interesting question. There is no way to do that at the moment. Do you have any ideeas how to implements that? We definitely can add `.always {}` block to detect future completion, but how do you think where and how to store an info about finished tasks?

**Comment by maximedegreve** [comment]
Not sure it was just an idea where you can ensure the crons don't overlap. 😁
