### ISSUE TITLE
Redefinition of modules CNIOOpenSSL and CCryptoOpenSSL

### ISSUE THREAD

**Issue by digoot** [MihaelIsaev/VaporCron#4]
Hello.

To begin with, I'm newbie with Vapor. I'm trying to install VaporCron 1.0.0 in a Vapor 3.0 project but I get an error that I don't know what is the problem and even I don't know how to solve it. I beg you to help me to solve this trouble. This is the compiler logs:

```
/Users/****/Git/****/****.xcodeproj/GeneratedModuleMap/CNIOOpenSSL/module.modulemap:1:8: error: redefinition of module 'CNIOOpenSSL'
module CNIOOpenSSL {
       ^
/Users/****/Library/Developer/Xcode/DerivedData/*****-bnccrqxqmxrreofqlnwptzgadojm/Build/Intermediates.noindex/GeneratedModuleMaps/macosx/CNIOOpenSSL.modulemap:1:8: note: previously defined here
module CNIOOpenSSL {
       ^
/Users/****/Git/****/****.xcodeproj/GeneratedModuleMap/CCryptoOpenSSL/module.modulemap:1:8: error: redefinition of module 'CCryptoOpenSSL'
module CCryptoOpenSSL {
       ^
/Users/****/Library/Developer/Xcode/DerivedData/****-bnccrqxqmxrreofqlnwptzgadojm/Build/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoOpenSSL.modulemap:1:8: note: previously defined here
module CCryptoOpenSSL {
       ^
/Users/****/Git/****/****.xcodeproj/GeneratedModuleMap/CNIOOpenSSL/module.modulemap:1:8: error: redefinition of module 'CNIOOpenSSL'
module CNIOOpenSSL {
       ^
/Users/****/Library/Developer/Xcode/DerivedData/****-bnccrqxqmxrreofqlnwptzgadojm/Build/Intermediates.noindex/GeneratedModuleMaps/macosx/CNIOOpenSSL.modulemap:1:8: note: previously defined here
module CNIOOpenSSL {
       ^
/Users/****/Git/****/****.xcodeproj/GeneratedModuleMap/CCryptoOpenSSL/module.modulemap:1:8: error: redefinition of module 'CCryptoOpenSSL'
module CCryptoOpenSSL {
       ^
/Users/****/Library/Developer/Xcode/DerivedData/****-bnccrqxqmxrreofqlnwptzgadojm/Build/Intermediates.noindex/GeneratedModuleMaps/macosx/CCryptoOpenSSL.modulemap:1:8: note: previously defined here
module CCryptoOpenSSL {
       ^
<unknown>:0: error: could not build Objective-C module 'CNIODarwin'
```

I have no clue what's wrong. Any idea?

**Comment by MihaelIsaev** [comment]
Hey it looks like even without `VaporCron` package you have the same errors, right?

**Comment by digoot** [comment]
If I remove `VaporCron` package, I have no errors, only a warning.

![Captura de pantalla 2020-05-05 a las 11 26 48](https://user-images.githubusercontent.com/16154094/81052385-9d79e600-8ec3-11ea-8b05-5c93e9ec8adc.png)

And this is what happened when I add `VaporCron` dependency:

![Captura de pantalla 2020-05-05 a las 11 20 45](https://user-images.githubusercontent.com/16154094/81052472-c69a7680-8ec3-11ea-9b7b-ecc9eecc77ed.png)

It could be my fault for sure, but I don't realize what I'm doing wrong.

**Comment by MihaelIsaev** [comment]
Could you show your `Package.swift`?

**Comment by digoot** [comment]
Of course!

```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "project",
    products: [
        .library(name: "project", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0"),
        
        // 📃 Swift minion for simple and lightweight XML parsing
        .package(url: "https://github.com/tadija/AEXML.git", from: "4.5.0"),
            
        // ⏱ Cron scheduler for Vapor
        .package(url: "https://github.com/MihaelIsaev/VaporCron.git", from:"1.0.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor", "AEXML", "VaporCron"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

**Comment by MihaelIsaev** [comment]
Hey, I've tried to reproduce problem and created empty project with exact the same `Package.swift` and it builds without any problems, check it out 
[diego.zip](https://github.com/MihaelIsaev/VaporCron/files/4580804/diego.zip)

I think you faced with cache problem.
If you are opening project via `Package.swift` directly then try to: close the project, inconsole execute `rm -rf .build && rm Package.resolved`, open the project again.
If you are opening project via `xcodeproj` file then close the project, execute in console `rm -rf .build && rm Package.resolved && swift package generate-xcodeproj`, when it finishes open the project again and try to build.
Also you could manually clear `derived data` and `xcode build` paths while project is closed.

**Comment by digoot** [comment]
Effectively! It was that. I was adding the dependency via Xcode. 

I'm used to using Cocoapods as dependency repository for a long time and this is my first time using Package. I didn't realize that the procedure to get the dependencies is the same way as Cocoapods, via CLI. That was my trouble. Doing this, 0 problems.

Thank you so much! I appreciate it.
