### ISSUE TITLE
Can't set timezone for job.

### ISSUE THREAD

**Issue by iwecon** [MihaelIsaev/VaporCron#7]

**Comment by goranche** [comment]
not sure why a timezone would be required on a cron style scheduler... 🤔

**Comment by iwecon** [comment]
> not sure why a timezone would be required on a cron style scheduler... 🤔

😂 I am in East Eight District, I am not too sensitive to the time zone, every time code scheduler and I need to confirm it many times.
Some tasks need to be carried out in my time zone. It is not convenient when converting...
